### ISSUE TITLE
What does Tji mean?

### ISSUE THREAD

**Issue by DuinoDu** [zhangboshen/A2J#1]
Hi Zhang, thanks for your awesome work.

What does Tji mean? 

> For joint j, in-plain target Tji denotes the 2D ground-truth in pixel coordinate transformed according to the cropped region.

Is Tji a gaussian heamap or circle-plate heatmap as descriped in `GRMI`?

More details are welcome.

Much thanks.

**Comment by zhangboshen** [comment]
Thanks for paying attention to our work!
Tji is 2D pixel coordinates, for joint j, it's a vector with length 2,
i.e., (x, y).  We do not make any gaussian heamaps. It is just the original
GT given by datasets itself.

Best Regards
Bohsen Zhang

Duino <notifications@github.com> 于2019年10月6日周日 下午11:05写道：
