### ISSUE TITLE
centre_pixel

### ISSUE THREAD

**Issue by HanLiangJ** [zhangboshen/A2J#13]
Hello! Thanks for your code!
I have a question that how to compute centre_pixel( icvl_center_test.mat ) in ICVL dataset? I have tried to average every 16 joints but failed to generate the same data as yours. Could you provide some details in this regard?
best wishes!

**Comment by DMCNerooo** [comment]
Hello! As the author says, this paper usesthe precomputed center results provided by _Gyeongsik et al._ which are generated from an additional center predictiion network. Find more details in [V2V-PoseNet](https://github.com/mks0601/V2V-PoseNet_RELEASE) . Hope it helps!

**Comment by HanLiangJ** [comment]
I see. Thank you!

**Comment by zhangboshen** [comment]
Sorry that I just see your comments yet.
And DMCNerooo is right!, we use the precomputed center results provided by Gyeongsik et al.
