### ISSUE TITLE
Center file computation of your paper

### ISSUE THREAD

**Issue by JoeHRIsaac** [zhangboshen/A2J#22]
May I know how to calculate the center files of the datasets you are using? I would like to do the same process to calculate for the BigHand2.2m dataset since it is not available. If you do have it, please let me know.
You report that you use precomputed centers from Gyeongsik et al. but when checking their values with yours, the x and y components are different (eg. 58.026760101318 -32.749855041504 404.03219604492 is the first center according to them while yours is  384.1734, 206.7794 and 404.0322)

**Comment by canuck6ix** [comment]
It's because centers in A2J are in UVD space whereas those in Gyeongsik et al. are in world space. You need to convert the centers from world to UVD space using [`world2pixel`](https://github.com/zhangboshen/A2J/blob/master/src/hands2017.py#L49)

**Comment by JoeHRIsaac** [comment]
If it is the UVD space then the raw values must be the same. However in the given snippet:
```python
center_test = scio.loadmat(center_file)['centre_pixel']
center_test = center_test.astype(np.float32)

centre_test_world = pixel2world(center_test.copy(), fx, fy, u0, v0)

centerlefttop_test = centre_test_world.copy()
centerlefttop_test[:,0,0] = centerlefttop_test[:,0,0]-xy_thres
centerlefttop_test[:,0,1] = centerlefttop_test[:,0,1]+xy_thres

centerrightbottom_test = centre_test_world.copy()
centerrightbottom_test[:,0,0] = centerrightbottom_test[:,0,0]+xy_thres
centerrightbottom_test[:,0,1] = centerrightbottom_test[:,0,1]-xy_thres

test_lefttop_pixel = world2pixel(centerlefttop_test, fx, fy, u0, v0)
test_rightbottom_pixel = world2pixel(centerrightbottom_test, fx, fy, u0, v0)
```

Here the world2pixel is used as you said. But the values (384.1734, 206.7794 and 404.0322) are from the file: center_file which is before the process was done. Then why is it different?

**Comment by zhangboshen** [comment]
> If it is the UVD space then the raw values must be the same. However in the given snippet:
> 
> ```python
> center_test = scio.loadmat(center_file)['centre_pixel']
> center_test = center_test.astype(np.float32)
> 
> centre_test_world = pixel2world(center_test.copy(), fx, fy, u0, v0)
> 
> centerlefttop_test = centre_test_world.copy()
> centerlefttop_test[:,0,0] = centerlefttop_test[:,0,0]-xy_thres
> centerlefttop_test[:,0,1] = centerlefttop_test[:,0,1]+xy_thres
> 
> centerrightbottom_test = centre_test_world.copy()
> centerrightbottom_test[:,0,0] = centerrightbottom_test[:,0,0]+xy_thres
> centerrightbottom_test[:,0,1] = centerrightbottom_test[:,0,1]-xy_thres
> 
> test_lefttop_pixel = world2pixel(centerlefttop_test, fx, fy, u0, v0)
> test_rightbottom_pixel = world2pixel(centerrightbottom_test, fx, fy, u0, v0)
> ```
> 
> Here the world2pixel is used as you said. But the values (384.1734, 206.7794 and 404.0322) are from the file: center_file which is before the process was done. Then why is it different?
That is because we already transformed the center point to UVD space, and test_lefttop_pixel and test_rightbottom_pixel are used to crop the hand-centered sub-image in world space.

**Comment by JoeHRIsaac** [comment]
Oh, I see it. Thank you very much.
