### ISSUE TITLE
Can't execute the training code

### ISSUE THREAD

**Issue by tanakahx** [zhangboshen/A2J#23]
Thank you for sharing your project code. It is really helpful to understand your paper.
BTW, I succeeded in running the inference code `src/nyu.py` properly
but I got some errors as follows when I ran the training code `src_train/nyu.py` in the commit https://github.com/zhangboshen/A2J/commit/6ab7346089260e1a52fa8c4ed7baa2857bfd08d5.

```
Traceback (most recent call last):
  File "nyu.py", line 10, in <module>
    import model as model
  File "D:\A2J\src_train\model.py", line 3, in <module>
    import resnet
ModuleNotFoundError: No module named 'resnet'
```

I fixed this error by importing `torchvision.models` instead of `resnet` in `model.py`.
```py
# import resnet
import torchvision.models as models
```

I also fixed the line 150 to use `torchvision.models` according to the modification above.
```py
        # modelPreTrain50 = resnet.resnet50(pretrained=True)
        modelPreTrain50 = models.resnet50(pretrained=True)
```

With all the modification above, however, I still got another error in `anchor.py` as follows.
```
Traceback (most recent call last):
  File "nyu.py", line 449, in <module>
    train()
  File "nyu.py", line 279, in train
    Cls_loss, Reg_loss = criterion(heads, label)
  File "D:\A2J\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\A2J\src_train\anchor.py", line 134, in forward
    reg = torch.unsqueeze(anchor,1) + regression #(w*h*A)*P*2
RuntimeError: The size of tensor a (1936) must match the size of tensor b (576) at non-singleton dimension 0
```

Could you please investigate the root cause of these errors? Did I miss something?

My environments are:
operating oystem
- Microsoft Windows 10

programming language
- Python 3.7.6
- PyTorch 1.4.0

**Comment by zhangboshen** [comment]
Oh, I am really sorry that I forget to upload resnet.py. 
And you should not use the resnet.py from torchvision, since we made a few modifications. 
You can refer to this file:
https://github.com/zhangboshen/A2J/blob/master/src/resnet.py

**Comment by tanakahx** [comment]
Hi, @zhangboshen 
Thank you for your prompt reply.
I succeeded in executing the training code by using `resnet.py`.
Many thanks!
