### ISSUE TITLE
Data augmentation problem

### ISSUE THREAD

**Issue by cherry-ing** [zhangboshen/A2J#26]
Hi, @zhangboshen ! Thank you for this work!
When I go through scr_train/nyu.py, I notice there is a parameter called `RandomOffsetDepth`. 
https://github.com/zhangboshen/A2J/blob/5848571cbb9d1911fc416ae6db186d9a8b0b5b8e/src_train/nyu.py#L153
It seems that all values in it are 0. And it has never been used after this line. Is it necessary to apply this augmentation?

**Comment by zhangboshen** [comment]
> Hi, @zhangboshen ! Thank you for this work!
> When I go through scr_train/nyu.py, I notice there is a parameter called `RandomOffsetDepth`.
> https://github.com/zhangboshen/A2J/blob/5848571cbb9d1911fc416ae6db186d9a8b0b5b8e/src_train/nyu.py#L153
> 
> 
> It seems that all values in it are 0. And it has never been used after this line. Is it necessary to apply this augmentation?


I am sorry I can't recall why this line of code exists. And since this line is not used anywhere, you can just comment it.
