### ISSUE TITLE
self.thres is unused in anchors.py

### ISSUE THREAD

**Issue by haydenshively** [zhangboshen/A2J#28]
The `self.thres` variable (present in both `A2J_loss` and `post_process` nn.Modules) is given a default value, yet never gets used. What is its purpose?

**Comment by zhangboshen** [comment]
Hi, `self.thres` is actually a variable of last version of our code, sorry that I forgot to remove it. You can remove it.

**Comment by haydenshively** [comment]
Great! Thanks so much.
