### ISSUE TITLE
Code for calculating mean and std

### ISSUE THREAD

**Issue by gitacct1800** [zhangboshen/A2J#29]
Hi I would like to understand how the mean and std for the images are obtained. Would you be able to provide the code? Thanks.

**Comment by zhangboshen** [comment]
@gitacct1800 , hi, you can see this discussion (https://github.com/zhangboshen/A2J/issues/12), I hope it helps.

**Comment by gitacct1800** [comment]
Thanks. I'll refer to the code there.
