### ISSUE TITLE
data_preprosess.py is missing

### ISSUE THREAD

**Issue by happyCodingSusan** [zhangboshen/A2J#31]
@zhangboshen , great impressive work! Thanks for sharing!

In your readme.md, you mentioned the following,

"After downloaded these datasets, you can follow the code from data folder (data_preprosess.py) to convert ICVL, NYU, ITOP, and K2HPD images to .mat files."

But I could not find it. Do you really have that file and need it?

**Comment by zhangboshen** [comment]
@happyCodingSusan  Hi, you can find data_preprocessing file in `data` folders, for example, this script transforms the original data into `mat` format: https://github.com/zhangboshen/A2J/blob/master/data/nyu/data_preprosess.m
