### ISSUE TITLE
spell mistake "data_preprosess.mat"

### ISSUE THREAD

**Issue by dejianwei** [zhangboshen/A2J#34]
I think right spell is “data_preprocess.mat”

mistake file name:
/data/icvl/data_preprosess.mat
/data/itop_side/data_preprosess.py
/data/k2hpd/data_preprosess.py
/data/nyu/data_preprosess.mat

**Comment by zhangboshen** [comment]
@dejianwei  Oh, sorry about that embarrassed mistake！
And thanks for your correction.
