### ISSUE TITLE
你好 K2hpd数据

### ISSUE THREAD

**Issue by mstc-xqp** [zhangboshen/A2J#38]
在src/K2hpd.py 19行里面
keypointsNumber = 19
但是 k2hpd的 ground_truth关键点是只有15的啊？

**Comment by zhangboshen** [comment]
@mstc-xqp    K2HPD是有19个点的2D标注的呀

**Comment by mstc-xqp** [comment]
请问一下 k2hpd 输出的结果 是一个 12*19*2的tensor

12是代表什么呢， 怎么通过这个获得19个关键点的 x,y坐标呢
