### ISSUE TITLE
Motivation of computing depth normal for ITOP and K2HPD datasets

### ISSUE THREAD

**Issue by bearpaw** [zhangboshen/A2J#43]
Hi @zhangboshen , I noticed that you precomputed the depth normal for human pose estimation tasks, while you use original depth maps for hand pose estimation. What's the motivation for this? Does original depth not work for human pose estimation? Thanks!

**Comment by zhangboshen** [comment]
Hi @bearpaw , Yes we did precomputed depth normal for ITOP dataset, the reason that we discard normal is that depth map itself can already achieve promising results.
