### ISSUE TITLE
Selecting anchor points with P = 0.02

### ISSUE THREAD

**Issue by Tekicho** [zhangboshen/A2J#54]
@zhangboshen i am confused where to put the code for selecting anchor points with p=0.02. Is it applied during training or inference or both? I am proudly using your great work in my research.

**Comment by zhangboshen** [comment]
@Tekicho 
Hi, selecting anchor points with threshold p=0.02 is only used to visualize these anchor points. And All anchor points contribute to  final prediction during training and testing.
And we are really glad to hear that our work may help you with your research!!

**Comment by Tekicho** [comment]
Ok, thank you @zhangboshen .
