### ISSUE TITLE
what's the mean of "depthFactor"?

### ISSUE THREAD

**Issue by lzcchl** [zhangboshen/A2J#55]
hello, what's the mean of "depthFactor" in src/itop_side.py or src/itop_top.py?

**Comment by zhangboshen** [comment]
@lzcchl , depthFactor is a unit converter,  the original annotated joints' depth in ITOP is meter, we scale it to better optimize the model.

**Comment by lzcchl** [comment]
Thanks for your reply. Is there any relevant guidance method? Why is it set to 50, can I set it 100 or 1000 or other number before training?

**Comment by zhangboshen** [comment]
@lzcchl  Hi, we set depthFactor as 50 empirically, and I think 100 may works fine. The unit on other datasets are usually mm, such as NYU_HANDS, so, when depthFactor=100 (or 50), many hyper-parameters can be shared on 2 datasets.

**Comment by lzcchl** [comment]
thanks!
