### ISSUE TITLE
Hands2017的数据是基于绝对3D坐标的，你们训练是基于UVD的， 请问Hands2017是如何训练的呢？

### ISSUE THREAD

**Issue by Stephenfang51** [zhangboshen/A2J#57]
Hands2017的数据只有提共绝对3D坐标的，但是你们训练NYU的则是基于UVD的， 请问Hands2017是如何训练的呢？

**Comment by zhangboshen** [comment]
@Stephenfang51 
根据相机内参将XYZ世界坐标转换为UVD的坐标就可以了；

**Comment by Stephenfang51** [comment]
@zhangboshen  谢谢回复， 那么D用的就是world coord里面的z-axis对吗？

**Comment by zhangboshen** [comment]
> @zhangboshen 谢谢回复， 那么D用的就是世界坐标里面的z-axis对吗？如果是的话 手部会随着距离摄像头越近 xy尺度会变大（正交投影的样子），但是原先世界坐标系的z值尺度并不变，这样得到的GroundTruth的手尺度应该就不对？（还是说并不影响？） 还是有方法可以缩放回原来手的大小

我的理解Z就是D，你举的例子手相较于摄像机距离变化的时候，GT的Z也就变了

**Comment by Stephenfang51** [comment]
@zhangboshen 很感谢回复，能简单的说说为什么GT会变吗? 您说的xyz转uvd， 应该只有xy才是？d直接沿用的z 对吧？ 不太理解这边变的意思， 十分感谢作者回复 ！

**Comment by zhangboshen** [comment]
> @zhangboshen 很感谢回复，能简单的说说为什么GT会变吗? 您说的xyz转uvd， 应该只有xy才是？d直接沿用的z 对吧？ 不太理解这边变的意思， 那么我能理解为模型输出的就是XY维度 为 176*176比例的UVD 三维关键点对吧？这个能还原到原始的世界坐标的维度吗？ 另外和直接用XYZ 然后用2.5D坐标当作GT来train有什么样的区别呢？ 如有时间烦请作者回复了 谢谢 ！

XYZ和UVD是可以互转的（Z就是D），我们使用数据集的XYZ坐标转到UVD坐标进行处理，是因为我们的模型输入的是图像而不是点云，你可以看我在主页给出来的可视化结果，有2D和3D的。如果是直接处理点云数据，那么直接使用XYZ进行监督就可以了

**Comment by Stephenfang51** [comment]
@zhangboshen  谢谢作者回复 因为我这虽然输入也是图像，但是一样用xyz监督，效果看着也还可以
