### ISSUE TITLE
reason for num_channel expansion?

### ISSUE THREAD

**Issue by Shreyas-NR** [zhangboshen/A2J#60]
Hi @zhangboshen,
In the Resent BackBone network,
Could you help me to understand the reason behind expanding the dimensions of the tensor passing it to 1D Conv?

As our input is 1D depth image of 288x288, the input to resnet50 backbone is 3x288x288. 

https://github.com/zhangboshen/A2J/blob/4c332f0ebff159d384af162a90b64ce89ea8d4b4/src_train/model.py#L156

```
        n, c, h, w = x.size()  # x: [B, 1, H ,W]
        
        x = x[:,0:1,:,:]  # depth
        x = x.expand(n,3,h,w)
              
        x = self.model.conv1(x)
```

Thanks,

**Comment by zhangboshen** [comment]
@Shreyas-NR  The expand operation simply converts the 1-channel depth map to 3-channel data, we doing so to meet the input requirement by ResNet (which is originally designed to handle 3-channel RGB images).

**Comment by Shreyas-NR** [comment]
Hi @zhangboshen 
Thanks for your quick response,

To get my understanding correct,
We have a depth image that is 1 channel grayscaled image with 288x288, 
then we expand it and obtain 3 channels, and all the 3 channels have grayscaled information
This is the Input to ResNet?

**Comment by zhangboshen** [comment]
> Hi @zhangboshen Thanks for your quick response,
> 
> To get my understanding correct, We have a depth image that is 1 channel grayscaled image with 288x288, then we expand it and obtain 3 channels, and all the 3 channels have grayscaled information This is the Input to ResNet?

----

Yes, that is correct.
