### ISSUE TITLE
Why are the Anchor-Points generated on a grid with spaces between them?

### ISSUE THREAD

**Issue by bmmtstb** [zhangboshen/A2J#63]
This is a question regarding the Paper in general, not the code.

The main Idea of A2J is to have anchor points from which distances to the respective joints are predicted or depth is predicted. I would argue that if you have more anchor points, the weighted sums of all the anchor points should be even better in terms of performance. So if you were to use every pixel as anchor point, you would have more computational burden but possibly better results?
Why reduce the anchor-point-resolution in the first place?

**Comment by zhangboshen** [comment]
@bmmtstb 
It is not always true that more anchor points brings better results, but more anchor points will cause more computational burden. In fact, we tried to set stride=1, means every pixels as an anchor point, the results can be found in our slides. An appropriate number of anchor points can balance the trade-off between performance and computation.
