### ISSUE TITLE
请问一下“需要手动下载的数据集”部分K2HPD的链接似乎被删除帖子了，能麻烦发一下这个包吗，网上没有找到，非常感谢！

### ISSUE THREAD

**Issue by JstYY** [zhangboshen/A2J#68]
请问一下“需要手动下载的数据集”部分K2HPD的链接似乎被删除帖子了，能麻烦发一下这个包吗，网上没有找到，非常感谢！

**Comment by zhangboshen** [comment]
> 请问一下“需要手动下载的数据集”部分K2HPD的链接似乎被删除帖子了，能麻烦发一下这个包吗，网上没有找到，非常感谢！

Try this one: https://drive.google.com/drive/folders/1Ny66UKA1Q8-6nSSK3F_dPrSU8cIUP4Gh

**Comment by JstYY** [comment]
感谢您！
