### ISSUE TITLE
Will you release the training code?

### ISSUE THREAD

**Issue by cherry-ing** [zhangboshen/A2J#7]
Hi, thank you for your great work.
I'm intending to train this model on my own dataset. Will you release the training code? 
Thank you very much!

**Comment by zhangboshen** [comment]
Hi, I am sorry that currently we can only release inference code, due to some reasons. But you are very welcome to reproduce our training code by following the implementation details in our paper.

**Comment by canuck6ix** [comment]
Hi Thanks for sharing your inference code. I was wondering if your issues are resolved so you can share your training code as well, thanks!
